### ISSUE TITLE
List view of offerings showing incorrect status messages

### ISSUE THREAD

**Issue by Bradymck** [district0x/name-bazaar#140]
UI not displaying name status correctly. Sometimes names show that they need ownership transferred when they already have. Sometimes they show a blank space and never load. 

**Image showing blank space and incorrect status message**
![Imgur](https://i.imgur.com/FKFGD8P.jpg)

**Image showing one of those names asking to transfer ownership that already has been transfered**
![Imgur](https://i.imgur.com/pONhrQT.jpg)

**Comment by alexjlevin** [comment]
So this issue is present on both Google Chrome and on Firefox as I tried both.

It seems that each time I refresh the page of "my offerings" it picks ones at random to say that they need the domain transferred in (which has already been done). When I individually click on them some change back to normal (to not needing the transfer) but not all. Then if I refresh the page different ones show the same error (asking for domain transfer). Very strange stuff. Thank you for your assistance in getting this resolved, I really appreciate it.
