### ISSUE TITLE
Some names are still getting stuck

### ISSUE THREAD

**Issue by Bradymck** [district0x/name-bazaar#141]
Names seem to be stuck at times not allowing a user to transfer ownership back to themself. I think this issue may be related to all the issues I posted today. Possibly due to a syncing issue. 

One name has already been released as mentioned in issue #138 . 

Other names that were listed months ago are having this issue. This issue was noticed by the user during the time our servers were having issues reaching limit and all our sites went down. 

**This is one example of a name that they can't transfer one minute but the next they can:**
![Imgur](https://i.imgur.com/Hxk5YU6.jpg)

**After refreshing a few times or waiting they suddenly can**
![Imgur](https://i.imgur.com/D8cXWO7.jpg) 

I think this is what caused the issue in #138 

If you have questions or need more info please let me know.

**Comment by alexjlevin** [comment]
So this issue is present on both Google Chrome and on Firefox as I tried both.

It seems that each time I refresh the page of "my offerings" it picks ones at random to say that they need the domain transferred in (which has already been done). When I individually click on them some change back to normal (to not needing the transfer) but not all. Then if I refresh the page different ones show the same error (asking for domain transfer). Very strange stuff. Thank you for your assistance in getting this resolved, I really appreciate it.

**Comment by Bradymck** [comment]
I have another name with this issue that needs to be fixed. Any ideas @fbielejec?
